### ISSUE TITLE
Worker sometimes taking and acknowledging jobs after Quit(), but not finishing them

### ISSUE THREAD

**Issue by tpiha** [jrallison/go-workers#43]
Hello @jrallison,

I'm using your library for my go project and it's an awesome lib. However, I have a small problem with it. Sometimes it takes and acknowledges a new job after Quit() has been called, but the job doesn't finish. I'm not sure how to reproduce it since it only happens sometimes, in my experience, more often with some longer running tasks.

I've created a small fix for it, but I'm pretty new to both go and your lib so I'm sure you could do it in some better way.

I added global Running bool variable in workers.go (https://gist.github.com/tpiha/b73bbaadeb4ada3e6f37#file-gistfile1-txt-L20) which I'm then setting to true right in the beginning of the Run function (https://gist.github.com/tpiha/b73bbaadeb4ada3e6f37#file-gistfile1-txt-L33) and same with Quit() function.

I'm also checking that variable in middleware.go:

https://gist.github.com/tpiha/0a9ec8644ea400aac83e#file-gistfile1-txt-L27

I've fixed this for my project, it's not an issue for me, but I'm still submitting bug if you wanna do something about it in the official code.

**Comment by jrallison** [comment]
Hey @tpiha,

That's true. When calling Quit(), you're telling the workers to start gracefully shutting down (rather than immediately exiting). This includes finishing up any jobs currently in process and/or any jobs fetched from redis and waiting to be processed.

Acknowledgement happens once the entire configured middleware chain finishes (including the job portion) and only if it returns true.

Your change seems to stop all middleware actions as soon as Quit() is called, which isn't a graceful shutdown.

I'm happy to help investigate the root cause here. Can you give me a failing test case or more information about your configuration and jobs you're performing which this occurs?

Thanks,
John

**Comment by tpiha** [comment]
The problem is, it just starts some new jobs, but doesn't finish them (even though it obviously acknowledges them since it doesn't retry on starting it again).

I'll try and create some test case scenario which can be easily reproduced.

**Comment by jrallison** [comment]
Awesome, thanks so much! I'd be very interested in fixing any issue that can cause what you're describing.

I'm happy to work on some test case scenario's as well, but I need some specific details about how you're using the library, the jobs you're running, etc to know where to start.

**Comment by jrallison** [comment]
Closing this since haven't heard of any other cases, and no response. If you'd like to revisit this, please open a new issue.
