### ISSUE TITLE
Scheduled jobs being "lost"

### ISSUE THREAD

**Issue by pjmuller** [jrallison/go-workers#73]
Hi there,

I'm using your package (with revision 287ed37)

I'm encountering some worrisome behavior (both in development as production).
When I'm quickly enqueuing scheduled jobs using `worker.EnqueueIn(...)` for some jobs (let's say 1 in 100) I do not get an error but a nice hash string of the created job ID. However the job is nowhere to be found. Not in "scheduled" and never arrives to "queued".

Did you already encounter this behavior? I'm only noticing it with scheduled jobs, not with directly enqueued jobs using `worker.Enqueue(...)`

Would be great to help me get this stability bug out of the code.

**Comment by jrallison** [comment]
Hey @pjmuller,

The result of `EnqueueIn` should place the job in one of two redis keys based on the options passed in.

In order to investigate further, I'd need some sort of way to reproduce the issue. If you can provide code (or a failing test case) that reproduces the issue, I'd be happy to start looking into it.

Thanks!

**Comment by pjmuller** [comment]
Hi @jrallison ,

thanks for the fast reply. Wow :)!

I have a very big golang project (> 10k lines of code). I'll try to make a demo app with just the necessary components.

In the meantime, 2 questions

- can you already point me some debugging ideas. For example "check this specific redis key", "monitor this kind of log", ...
- Did you already encounter this kind of behavior yourself? What was it linked to?

Greetings,
PJ
