### ISSUE TITLE
Retry Jobs Not Showing in Sidekiq Retry List in Web UI

### ISSUE THREAD

**Issue by ryanjavens** [jrallison/go-workers#76]
Hey everyone,

I was wondering if I could get any input on this. I'm using the default retry middleware in this library and calling the panic method within my jobs when an error occurs. The jobs are being retried, but they are not being placed in the retry queue on the Sidekiq UI. I'm a bit of a Golang beginner and I've tried to take a look into the retry middleware source code to find answers without much luck. Are these jobs not being put Sidekiq's retry queue because they're simply being requeued within this library or am I just goofing something up?

I look forward to any input that you may have! 😄 

Thanks!

**Comment by jrallison** [comment]
Hey Ryan,

Sorry for the delay in responding. This project's default retry middleware places retry jobs in a separate redis key.

This was done in order to not break use-cases (like ours when we were transitioning from Ruby to Golang) that have both sidekiq and go-workers running at once. Sidekiq queues are separated, but the retry key is global. Using the same key would result in ruby sidekiq workers seeing failed jobs from go-workers, and vice versa.

As always, all middleware is pluggable and you can modify it to place failed jobs to retry in whatever redis key you wish.
